# Generated by Django 4.1.3 on 2022-12-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardmanager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardModel',
        ),
    ]
