# Generated by Django 4.1.3 on 2022-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.PositiveBigIntegerField()),
                ('number', models.PositiveBigIntegerField()),
                ('release_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('use_date', models.DateTimeField()),
                ('sum', models.IntegerField()),
            ],
        ),
    ]
