# Generated by Django 4.1.3 on 2022-12-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cardmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodel',
            name='user',
        ),
    ]
