# Generated by Django 4.1.3 on 2022-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cardmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='status',
            field=models.CharField(choices=[('Not Active', 'NOT_ACTIVE'), ('Active', 'ACTIVE'), ('Expired', 'EXPIRED')], default='Not Active', max_length=10),
        ),
    ]
