# Generated by Django 4.1.3 on 2022-12-06 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cardmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 6, 59, 57, 761327, tzinfo=datetime.timezone.utc)),
        ),
    ]
