# Generated by Django 4.1.3 on 2022-12-06 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cardmodel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
