# Generated by Django 4.1.3 on 2022-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cardmodel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
